In [18]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

keyparam="APPID"
def cleanprint(str):
    cleanstr = re.sub(keyparam+'=.*\&', '', str,  flags=re.DOTALL)
    cleanstr = re.sub(keyparam+'=.*$', '', cleanstr,  flags=re.DOTALL)
    return cleanstr

In [19]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Saint Helens,GB,2022-04-30 22:26:01,53.4500,-2.7333,51.10,85,100,9.22
1,1,Rikitea,PF,2022-04-30 22:26:01,-23.1203,-134.9692,75.54,77,61,10.58
2,2,Olafsvik,IS,2022-04-30 22:26:02,64.8945,-23.7142,44.46,84,99,15.14
3,3,Esperance,AU,2022-04-30 22:26:02,-33.8667,121.9000,51.64,66,0,6.89
4,4,Albany,US,2022-04-30 22:26:03,42.6001,-73.9662,61.57,30,88,9.44

In [20]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [21]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [22]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat","Lng"]]
locations

         Lat       Lng
0    53.4500   -2.7333
1   -23.1203 -134.9692
2    64.8945  -23.7142
3   -33.8667  121.9000
4    42.6001  -73.9662
..       ...       ...
545  70.0167  135.6000
546  21.3156 -158.0072
547  23.3833 -105.3833
548 -26.5020   17.1583
549  41.3231   19.4414

[550 rows x 2 columns]

In [23]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps=[]
temps = [max(temp,0) for temp in max_temp]
temps

[51.1,
 75.54,
 44.46,
 51.64,
 61.57,
 81.95,
 67.69,
 85.08,
 53.49,
 74.03,
 18.63,
 40.66,
 60.73,
 68.04,
 80.74,
 41.11,
 55.18,
 58.24,
 54.9,
 51.93,
 60.91,
 78.33,
 80.89,
 76.59,
 54.84,
 58.5,
 78.53,
 78.69,
 59.49,
 79.34,
 96.01,
 65.71,
 62.24,
 80.58,
 75.2,
 52.88,
 67.24,
 48.2,
 35.6,
 78.78,
 77.25,
 61.32,
 18.95,
 77.11,
 41.16,
 13.59,
 78.96,
 51.58,
 55.18,
 33.15,
 57.47,
 46.69,
 21.22,
 65.41,
 58.03,
 56.3,
 55.56,
 40.51,
 60.42,
 52.02,
 64.33,
 8.15,
 17.96,
 82.45,
 76.78,
 83.01,
 71.76,
 13.33,
 58.23,
 17.28,
 82.33,
 50.07,
 80.76,
 75.22,
 38.3,
 56.08,
 10.24,
 17.83,
 75.9,
 48.02,
 82.94,
 74.89,
 76.24,
 58.57,
 76.21,
 71.92,
 80.55,
 82.54,
 67.17,
 64.76,
 52.88,
 50.32,
 82.69,
 14.56,
 86.41,
 60.98,
 82.09,
 59.81,
 87.01,
 78.76,
 39.31,
 77.5,
 23.22,
 93.13,
 68.85,
 89.85,
 83.01,
 78.91,
 39.09,
 46.8,
 80.13,
 64.85,
 78.01,
 36.12,
 78.85,
 39.76,
 38.3,
 68.45,
 66.83,
 66.22,
 43.47,
 31.12,
 60.22,
 27.54,
 58.86,
 60.67,
 12.94,
 78.06,
 74.64,
 59.11,
 74.37,
 44.04,
 88.2,
 61.61,
 35.37,
 82.54,
 74.28,
 59.79,
 79.12,
 18.32,
 79.29,
 56.12,
 66.72,
 78.19,
 85.41,
 31.15,
 76.44,
 62.69,
 55.87,
 73.8,
 62.42,
 75.38,
 38.17,
 66.83,
 62.35,
 35.76,
 79.07,
 53.56,
 78.46,
 84.25,
 29.01,
 80.47,
 20.82,
 33.57,
 36.55,
 41.0,
 65.21,
 81.28,
 64.49,
 60.91,
 55.0,
 59.67,
 82.47,
 88.38,
 92.14,
 85.59,
 83.39,
 87.46,
 62.92,
 47.79,
 60.42,
 36.68,
 52.29,
 72.88,
 54.01,
 60.69,
 73.44,
 68.11,
 31.42,
 51.33,
 35.42,
 53.65,
 77.29,
 83.26,
 56.08,
 62.13,
 51.3,
 81.72,
 60.69,
 78.87,
 44.28,
 44.76,
 49.01,
 7.74,
 85.06,
 91.53,
 82.17,
 81.57,
 45.52,
 31.64,
 39.02,
 69.58,
 53.62,
 73.38,
 74.93,
 79.84,
 37.15,
 85.46,
 26.13,
 84.0,
 70.66,
 51.26,
 69.35,
 79.41,
 53.82,
 77.7,
 53.47,
 92.35,
 83.73,
 40.55,
 66.6,
 60.53,
 57.38,
 53.8,
 36.45,
 43.36,
 75.07,
 80.92,
 59.49,
 66.27,
 74.98,
 58.82,
 70.72,
 84.83,
 85.75,
 67.39,
 80.58,
 89.85,
 61.97,
 16.5,
 52.34,
 81.12,
 58.28,
 83.03,
 92.52,
 59.5,
 77.38,
 51.31,
 78.8,
 60.46,
 32.18,
 49.89,
 81.21,
 65.7,
 48.24,
 54.68,
 47.75,
 77.34,
 50.74,
 77.45,
 50.83,
 54.09,
 68.67,
 44.85,
 9.12,
 50.11,
 68.72,
 23.25,
 32.47,
 82.45,
 35.42,
 56.93,
 64.18,
 59.97,
 43.65,
 61.88,
 60.26,
 82.94,
 23.65,
 28.15,
 42.76,
 79.88,
 60.64,
 74.91,
 11.16,
 86.81,
 78.55,
 50.61,
 78.98,
 77.45,
 70.92,
 71.02,
 59.45,
 50.61,
 39.79,
 85.62,
 62.22,
 67.95,
 86.13,
 82.08,
 82.58,
 53.15,
 71.15,
 82.47,
 65.46,
 20.39,
 8.65,
 46.35,
 75.43,
 33.78,
 68.4,
 84.38,
 75.99,
 39.42,
 45.97,
 72.61,
 45.55,
 81.95,
 57.99,
 89.78,
 84.9,
 38.17,
 48.15,
 59.14,
 25.7,
 80.58,
 78.84,
 74.53,
 54.09,
 80.62,
 55.51,
 60.08,
 52.66,
 80.98,
 69.26,
 50.76,
 77.43,
 64.2,
 77.95,
 71.82,
 60.8,
 58.19,
 77.95,
 60.71,
 46.6,
 34.3,
 37.94,
 48.85,
 82.27,
 55.42,
 21.16,
 80.65,
 39.6,
 73.44,
 88.29,
 81.03,
 46.53,
 80.92,
 24.53,
 60.08,
 46.85,
 90.27,
 80.6,
 51.66,
 73.33,
 67.53,
 53.92,
 28.63,
 77.09,
 47.68,
 42.89,
 76.96,
 56.84,
 73.44,
 38.77,
 75.34,
 57.13,
 24.82,
 18.21,
 43.23,
 51.15,
 53.11,
 48.33,
 55.6,
 37.18,
 56.71,
 86.09,
 77.18,
 72.34,
 50.32,
 35.58,
 57.49,
 48.6,
 60.87,
 65.8,
 87.1,
 87.53,
 81.82,
 72.34,
 76.51,
 47.98,
 46.85,
 66.45,
 88.52,
 42.22,
 42.76,
 57.92,
 90.32,
 79.29,
 51.17,
 64.38,
 76.96,
 69.42,
 44.55,
 72.82,
 52.09,
 82.31,
 80.65,
 61.25,
 57.6,
 82.24,
 76.03,
 80.64,
 48.04,
 29.08,
 31.87,
 42.96,
 20.98,
 55.65,
 75.58,
 55.08,
 50.86,
 24.91,
 59.94,
 44.56,
 30.07,
 76.15,
 55.92,
 24.6,
 27.21,
 79.57,
 36.37,
 73.22,
 79.47,
 68.22,
 75.9,
 50.09,
 67.17,
 74.46,
 60.69,
 79.83,
 71.42,
 52.14,
 85.84,
 75.18,
 75.31,
 68.5,
 84.61,
 65.32,
 59.14,
 51.85,
 73.35,
 23.63,
 74.91,
 75.74,
 92.03,
 34.34,
 70.99,
 79.41,
 59.25,
 83.14,
 59.76,
 63.99,
 39.25,
 88.39,
 60.35,
 82.45,
 87.21,
 76.95,
 43.92,
 80.62,
 78.69,
 60.89,
 21.51,
 48.92,
 68.05,
 78.51,
 40.35,
 68.05,
 85.8,
 54.3,
 66.18,
 60.22,
 23.88,
 74.79,
 75.79,
 75.33,
 71.4,
 59.2,
 43.59,
 30.15,
 82.96,
 79.97,
 59.77,
 81.05,
 21.65,
 95.56,
 15.49,
 80.29,
 90.59,
 75.34,
 72.97,
 68.02,
 87.57,
 47.75,
 78.01,
 45.52,
 78.51,
 89.17,
 41.0,
 82.62,
 66.63,
 68.45,
 27.05,
 87.33,
 31.39,
 64.58,
 51.82,
 79.79,
 62.06,
 46.31,
 80.56,
 70.65,
 53.71,
 87.08,
 23.68,
 82.35,
 75.79,
 55.18,
 53.78]

In [24]:
# Assign the figure variable.
fig = gmaps.figure(center=(30.0,31.0),zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations,weights=temps,dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
cloudiness = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=cloudiness, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [27]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind_speed = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind_speed, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [30]:
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) 
                                       & (city_data_df["Max Temp"] <= max_temp) ]
preferred_cities_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Rikitea,PF,2022-04-30 22:26:01,-23.1203,-134.9692,75.54,77,61,10.58
5,5,Floriano,BR,2022-04-30 22:26:03,-6.7669,-43.0225,81.95,47,98,2.19
7,7,Bosaso,SO,2022-04-30 22:26:04,11.2842,49.1816,85.08,66,46,1.12
14,14,Banda Aceh,ID,2022-04-30 22:26:07,5.5577,95.3222,80.74,82,100,7.05
21,21,Dicabisagan,PH,2022-04-30 22:26:11,17.0818,122.4157,78.33,86,65,4.85

In [31]:
preferred_cities_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 172 entries, 1 to 547
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City_ID     172 non-null    int64
 1   City        172 non-null    object
 2   Country     172 non-null    object
 3   Date        172 non-null    object
 4   Lat         172 non-null    float64
 5   Lng         172 non-null    float64
 6   Max Temp    172 non-null    float64
 7   Humidity    172 non-null    int64
 8   Cloudiness  172 non-null    int64
 9   Wind Speed  172 non-null    float64
dtypes: float64(4), int64(3), object(3)
memory usage: 14.8+ KB

In [32]:
preferred_cities_df.count()

City_ID       172
City          172
Country       172
Date          172
Lat           172
Lng           172
Max Temp      172
Humidity      172
Cloudiness    172
Wind Speed    172
dtype: int64

In [33]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
preferred_cities_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Rikitea,PF,2022-04-30 22:26:01,-23.1203,-134.9692,75.54,77,61,10.58
5,5,Floriano,BR,2022-04-30 22:26:03,-6.7669,-43.0225,81.95,47,98,2.19
7,7,Bosaso,SO,2022-04-30 22:26:04,11.2842,49.1816,85.08,66,46,1.12
14,14,Banda Aceh,ID,2022-04-30 22:26:07,5.5577,95.3222,80.74,82,100,7.05
21,21,Dicabisagan,PH,2022-04-30 22:26:11,17.0818,122.4157,78.33,86,65,4.85
...,...,...,...,...,...,...,...,...,...,...
538,538,Candelaria,PH,2022-04-30 22:39:55,13.9311,121.4233,79.79,83,99,5.41
541,541,Madanapalle,IN,2022-04-30 22:40:54,13.5500,78.5000,80.56,60,32,4.45
544,544,Thanesar,IN,2022-04-30 22:40:56,29.9833,76.8167,87.08,14,90,7.49
546,546,Ewa Beach,US,2022-04-30 22:40:57,21.3156,-158.0072,82.35,60,75,21.85
547,547,Pueblo Nuevo,MX,2022-04-30 22:40:57,23.3833,-105.3833,75.79,19,6,8.88

In [36]:
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat       Lng Hotel Name
1          Rikitea      PF     75.54 -23.1203 -134.9692
5         Floriano      BR     81.95  -6.7669  -43.0225
7           Bosaso      SO     85.08  11.2842   49.1816
14      Banda Aceh      ID     80.74   5.5577   95.3222
21     Dicabisagan      PH     78.33  17.0818  122.4157
22      Butaritari      KI     80.89   3.0707  172.7902
23  Saint-Philippe      RE     76.59 -21.3585   55.7679
26          Olinda      BR     78.53  -8.0089  -34.8553
27          Tambun      ID     78.69  -6.2641  107.0712
29          Ranong      TH     79.34   9.9658   98.6348

In [37]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [53]:
# Iterate through the DataFrame.

for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url,params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index,"Hotel Name"] = hotels["results"][0]["name"]
    except(IndexError):
        print(f'Hotel Not Found in {row["City"]}... Skipping')

Hotel Not Found in Goundam... Skipping
Hotel Not Found in Avera... Skipping
Hotel Not Found in Benin... Skipping
Hotel Not Found in Adrar... Skipping
Hotel Not Found in Thinadhoo... Skipping
Hotel Not Found in Poum... Skipping
Hotel Not Found in Edd... Skipping
Hotel Not Found in Pueblo Nuevo... Skipping

In [54]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Rikitea,PF,75.54,-23.1203,-134.9692,People ThankYou
5,Floriano,BR,81.95,-6.7669,-43.0225,Hotel Maktub
7,Bosaso,SO,85.08,11.2842,49.1816,Red Sea Hotel
14,Banda Aceh,ID,80.74,5.5577,95.3222,OYO 884 Rumoh PMI Hotel
21,Dicabisagan,PH,78.33,17.0818,122.4157,Nancy Montanes Bernardo
...,...,...,...,...,...,...
538,Candelaria,PH,79.79,13.9311,121.4233,Casa de Provincia
541,Madanapalle,IN,80.56,13.5500,78.5000,Prithvi Lodge
544,Thanesar,IN,87.08,29.9833,76.8167,Hotel M.G Grand
546,Ewa Beach,US,82.35,21.3156,-158.0072,Base Lodging
547,Pueblo Nuevo,MX,75.79,23.3833,-105.3833,

In [55]:
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 172 entries, 1 to 547
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        172 non-null    object
 1   Country     172 non-null    object
 2   Max Temp    172 non-null    float64
 3   Lat         172 non-null    float64
 4   Lng         172 non-null    float64
 5   Hotel Name  172 non-null    object
dtypes: float64(3), object(3)
memory usage: 13.5+ KB

In [56]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [57]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [59]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
hotel_info

['\n<dl>\n<dt>Hotel Name</dt><dd>People ThankYou</dd>\n<dt>City</dt><dd>Rikitea</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Max Temp</dt><dd>75.54 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Maktub</dd>\n<dt>City</dt><dd>Floriano</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>81.95 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Red Sea Hotel</dd>\n<dt>City</dt><dd>Bosaso</dd>\n<dt>Country</dt><dd>SO</dd>\n<dt>Max Temp</dt><dd>85.08 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>OYO 884 Rumoh PMI Hotel</dd>\n<dt>City</dt><dd>Banda Aceh</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>80.74 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Nancy Montanes Bernardo</dd>\n<dt>City</dt><dd>Dicabisagan</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>78.33 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Isles Sunset Lodge</dd>\n<dt>City</dt><dd>Butaritari</dd>\n<dt>Country</dt><dd>KI</dd>\n<dt>Max Temp</dt><dd>80.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Chambres d\'hôte "La Trinité"</dd>\n<dt>City</dt><dd>Saint-Philippe</dd>\n<dt>Country</dt><dd>RE</dd>\n<dt>Max Temp</dt><dd>76.59 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Flat Quatro Rodas Olinda</dd>\n<dt>City</dt><dd>Olinda</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>78.53 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Metland Hotel Bekasi</dd>\n<dt>City</dt><dd>Tambun</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>78.69 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Tinidee Hotel@Ranong</dd>\n<dt>City</dt><dd>Ranong</dd>\n<dt>Country</dt><dd>TH</dd>\n<dt>Max Temp</dt><dd>79.34 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sheraton Kauai Coconut Beach Resort</dd>\n<dt>City</dt><dd>Kapaa</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>80.58 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Grage Hotel Bengkulu</dd>\n<dt>City</dt><dd>Bengkulu</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>75.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>TumbleWeed RV Park</dd>\n<dt>City</dt><dd>Meadow Lake</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>78.78 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Casa Tia Villa</dd>\n<dt>City</dt><dd>Bambous Virieux</dd>\n<dt>Country</dt><dd>MU</dd>\n<dt>Max Temp</dt><dd>77.25 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sunrise Attitude Hotel</dd>\n<dt>City</dt><dd>Quatre Cocos</dd>\n<dt>Country</dt><dd>MU</dd>\n<dt>Max Temp</dt><dd>77.11 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Keleti Beach Resort</dd>\n<dt>City</dt><dd>Vaini</dd>\n<dt>Country</dt><dd>TO</dd>\n<dt>Max Temp</dt><dd>78.96 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Paradise Inn</dd>\n<dt>City</dt><dd>Avarua</dd>\n<dt>Country</dt><dd>CK</dd>\n<dt>Max Temp</dt><dd>82.45 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Apartamentos Rincon La Roca</dd>\n<dt>City</dt><dd>Sanchez</dd>\n<dt>Country</dt><dd>DO</dd>\n<dt>Max Temp</dt><dd>76.78 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Erlyn’s Sta Rosa City Home</dd>\n<dt>City</dt><dd>Santa Rosa</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>83.01 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Cititel Penang</dd>\n<dt>City</dt><dd>Georgetown</dd>\n<dt>Country</dt><dd>MY</dd>\n<dt>Max Temp</dt><dd>82.33 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Raybow International Hotel</dd>\n<dt>City</dt><dd>Takoradi</dd>\n<dt>Country</dt><dd>GH</dd>\n<dt>Max Temp</dt><dd>80.76 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Nusantara I</dd>\n<dt>City</dt><dd>Nabire</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>75.22 °F</dd>\n</dl>\n',
 "\n<dl>\n<dt>Hotel Name</dt><dd>Résidence d'Hôtes Bapedy</dd>\n<dt>City</dt><dd>Fougamou</dd>\n<dt>Country</dt><dd>GA</dd>\n<dt>Max Temp</dt><dd>75.9 °F</dd>\n</dl>\n",
 '\n<dl>\n<dt>Hotel Name</dt><dd>Best Western Plus Abbey Inn</dd>\n<dt>City</dt><dd>Saint George</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>82.94 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Paradise Hotel</dd>\n<dt>City</dt><dd>Wanning</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Max Temp</dt><dd>76.24 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Grand Plaza Hotel - St. Pete Beach</dd>\n<dt>City</dt><dd>Saint Pete Beach</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>76.21 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Savli Resort/Hotel - Shrivardhan</dd>\n<dt>City</dt><dd>Srivardhan</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>80.55 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Swiss-Belhotel Ambon</dd>\n<dt>City</dt><dd>Ambon</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>82.54 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Uruna Bay Retreat</dd>\n<dt>City</dt><dd>Kieta</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>82.69 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>BALAJI KITCHENS</dd>\n<dt>City</dt><dd>Gudur</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>86.41 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hôtel Le Dronmi</dd>\n<dt>City</dt><dd>Cayenne</dd>\n<dt>Country</dt><dd>GF</dd>\n<dt>Max Temp</dt><dd>82.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Boomtown Casino & Hotel New Orleans</dd>\n<dt>City</dt><dd>Estelle</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>87.01 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Finch Bay Galapagos Hotel</dd>\n<dt>City</dt><dd>Puerto Ayora</dd>\n<dt>Country</dt><dd>EC</dd>\n<dt>Max Temp</dt><dd>78.76 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Novo Hotel</dd>\n<dt>City</dt><dd>Manacapuru</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.5 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Goundam</dd>\n<dt>Country</dt><dd>ML</dd>\n<dt>Max Temp</dt><dd>89.85 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>East Arnhem Real Estate</dd>\n<dt>City</dt><dd>Nhulunbuy</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>83.01 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Villa Enata</dd>\n<dt>City</dt><dd>Atuona</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Max Temp</dt><dd>78.91 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Alrwasi Hotel</dd>\n<dt>City</dt><dd>Hun</dd>\n<dt>Country</dt><dd>LY</dd>\n<dt>Max Temp</dt><dd>80.13 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Kost Pria</dd>\n<dt>City</dt><dd>Meulaboh</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>78.01 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Holiday Inn Express Lompoc, an IHG Hotel</dd>\n<dt>City</dt><dd>Lompoc</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>78.85 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Best Western Patriots Point</dd>\n<dt>City</dt><dd>Mount Pleasant</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>78.06 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Posada Villa Nela</dd>\n<dt>City</dt><dd>Upata</dd>\n<dt>Country</dt><dd>VE</dd>\n<dt>Max Temp</dt><dd>88.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Avera</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>82.54 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>The Inn At Schofield</dd>\n<dt>City</dt><dd>Wahiawa</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>79.12 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hilo Hawaiian Hotel</dd>\n<dt>City</dt><dd>Hilo</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>79.29 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Balaji tifen & meals veg & non veg hotel</dd>\n<dt>City</dt><dd>Palasa</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>78.19 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Marriage lawn</dd>\n<dt>City</dt><dd>Jhinjhak</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>85.41 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Ponta Verde Maceió</dd>\n<dt>City</dt><dd>Maceio</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>76.44 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Mini Hotel Central</dd>\n<dt>City</dt><dd>Victoria</dd>\n<dt>Country</dt><dd>HK</dd>\n<dt>Max Temp</dt><dd>75.38 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel les Arcades</dd>\n<dt>City</dt><dd>Moroni</dd>\n<dt>Country</dt><dd>KM</dd>\n<dt>Max Temp</dt><dd>79.07 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Holiday Inn Mayaguez & Tropical Casino, an IHG Hotel</dd>\n<dt>City</dt><dd>Mayaguez</dd>\n<dt>Country</dt><dd>PR</dd>\n<dt>Max Temp</dt><dd>78.46 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Iftin hotel hobyo</dd>\n<dt>City</dt><dd>Hobyo</dd>\n<dt>Country</dt><dd>SO</dd>\n<dt>Max Temp</dt><dd>84.25 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>INN NEW HORIZON</dd>\n<dt>City</dt><dd>Touros</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>80.47 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Bora-Bora Pearl Beach Resort & Spa</dd>\n<dt>City</dt><dd>Faanui</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Max Temp</dt><dd>81.28 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Kimbe Bay Hotel</dd>\n<dt>City</dt><dd>Kimbe</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>82.47 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>SpringHill Suites by Marriott Las Cruces</dd>\n<dt>City</dt><dd>Las Cruces</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>88.38 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Anand</dd>\n<dt>City</dt><dd>Khambhat</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>85.59 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Seagulls Inn Namatani</dd>\n<dt>City</dt><dd>Namatanai</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>83.39 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hôtel Trois Étoiles de Biltine</dd>\n<dt>City</dt><dd>Biltine</dd>\n<dt>Country</dt><dd>TD</dd>\n<dt>Max Temp</dt><dd>87.46 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shandrani Beachcomber Resort & Spa</dd>\n<dt>City</dt><dd>Mahebourg</dd>\n<dt>Country</dt><dd>MU</dd>\n<dt>Max Temp</dt><dd>77.29 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Cossam Guest House</dd>\n<dt>City</dt><dd>Finschhafen</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>83.26 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Leumerus Bungalows</dd>\n<dt>City</dt><dd>Sola</dd>\n<dt>Country</dt><dd>VU</dd>\n<dt>Max Temp</dt><dd>81.72 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Benin</dd>\n<dt>Country</dt><dd>BJ</dd>\n<dt>Max Temp</dt><dd>78.87 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Scoop Guest House</dd>\n<dt>City</dt><dd>Hithadhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Max Temp</dt><dd>85.06 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Areia Branca Apart Hotel</dd>\n<dt>City</dt><dd>Areia Branca</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>82.17 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Lords Inn Somnath</dd>\n<dt>City</dt><dd>Veraval</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>81.57 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Adrar</dd>\n<dt>Country</dt><dd>MR</dd>\n<dt>Max Temp</dt><dd>79.84 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Medhufushi Island Resort</dd>\n<dt>City</dt><dd>Muli</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Max Temp</dt><dd>85.46 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Maringe Lagoon Lodge</dd>\n<dt>City</dt><dd>Buala</dd>\n<dt>Country</dt><dd>SB</dd>\n<dt>Max Temp</dt><dd>84.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Leonardo Family Beach House 1</dd>\n<dt>City</dt><dd>Pundaguitan</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>79.41 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel BR 364</dd>\n<dt>City</dt><dd>Cacoal</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.7 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Nusa Island Retreat</dd>\n<dt>City</dt><dd>Kavieng</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>83.73 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel e Restaurante Uirapuru (Márcio uirapuru )Em São Domingos -Go</dd>\n<dt>City</dt><dd>Sao Domingos</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>75.07 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Foundation Taaj Asala for Historical Research and Archeology</dd>\n<dt>City</dt><dd>Sabha</dd>\n<dt>Country</dt><dd>LY</dd>\n<dt>Max Temp</dt><dd>80.92 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Fazenda 4 cantos</dd>\n<dt>City</dt><dd>Ladario</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>84.83 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Thinadhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Max Temp</dt><dd>85.75 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Kununurra</dd>\n<dt>City</dt><dd>Kununurra</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>80.58 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hôtel Campement</dd>\n<dt>City</dt><dd>Niono</dd>\n<dt>Country</dt><dd>ML</dd>\n<dt>Max Temp</dt><dd>89.85 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Akwa Reef Lodge</dd>\n<dt>City</dt><dd>Ailigandi</dd>\n<dt>Country</dt><dd>PA</dd>\n<dt>Max Temp</dt><dd>81.12 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>M.O.S. Logística - Filial Fortaleza</dd>\n<dt>City</dt><dd>Caucaia</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>83.03 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shanti Maurice Resort & Spa</dd>\n<dt>City</dt><dd>Souillac</dd>\n<dt>Country</dt><dd>MU</dd>\n<dt>Max Temp</dt><dd>77.38 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Tarawa Boutique Hotel</dd>\n<dt>City</dt><dd>Bairiki</dd>\n<dt>Country</dt><dd>KI</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Atlantis Hotel</dd>\n<dt>City</dt><dd>Bathsheba</dd>\n<dt>Country</dt><dd>BB</dd>\n<dt>Max Temp</dt><dd>81.21 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Real Hotel</dd>\n<dt>City</dt><dd>Sao Raimundo Nonato</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.34 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Mövenpick Qassim</dd>\n<dt>City</dt><dd>Buraydah</dd>\n<dt>Country</dt><dd>SA</dd>\n<dt>Max Temp</dt><dd>77.45 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Gobi centre</dd>\n<dt>City</dt><dd>Magadi</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>82.45 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Lorengau Harbourside Hotel</dd>\n<dt>City</dt><dd>Lorengau</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Max Temp</dt><dd>82.94 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Kalabi INN</dd>\n<dt>City</dt><dd>Ventanas</dd>\n<dt>Country</dt><dd>EC</dd>\n<dt>Max Temp</dt><dd>79.88 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Uribia</dd>\n<dt>City</dt><dd>Uribia</dd>\n<dt>Country</dt><dd>CO</dd>\n<dt>Max Temp</dt><dd>86.81 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>BKD</dd>\n<dt>City</dt><dd>Chakulia</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>78.55 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hampton Inn Russellville</dd>\n<dt>City</dt><dd>Russellville</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>78.98 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Salinas Park Resort Maçarico AP101</dd>\n<dt>City</dt><dd>Salinopolis</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.45 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Al-Mustafa Hotel</dd>\n<dt>City</dt><dd>Uthal</dd>\n<dt>Country</dt><dd>PK</dd>\n<dt>Max Temp</dt><dd>85.62 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Cartagena Marlin hostel</dd>\n<dt>City</dt><dd>Soledad</dd>\n<dt>Country</dt><dd>CO</dd>\n<dt>Max Temp</dt><dd>86.13 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Radisson Grenada Beach Resort</dd>\n<dt>City</dt><dd>Saint-Georges</dd>\n<dt>Country</dt><dd>GD</dd>\n<dt>Max Temp</dt><dd>82.08 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Narayan Avezika Comfort</dd>\n<dt>City</dt><dd>Dwarka</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Max Temp</dt><dd>82.58 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>HOTEL QUINTA ANTIGUA</dd>\n<dt>City</dt><dd>Lazaro Cardenas</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Max Temp</dt><dd>82.47 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Kou-Bugny</dd>\n<dt>City</dt><dd>Vao</dd>\n<dt>Country</dt><dd>NC</dd>\n<dt>Max Temp</dt><dd>75.43 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Grand Vilia Hotel</dd>\n<dt>City</dt><dd>Tual</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Max Temp</dt><dd>84.38 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel cruz de ouro</dd>\n<dt>City</dt><dd>Rio De Janeiro</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>75.99 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Oumou Elghoura</dd>\n<dt>City</dt><dd>Atar</dd>\n<dt>Country</dt><dd>MR</dd>\n<dt>Max Temp</dt><dd>81.95 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Auto Hotel El Soñador</dd>\n<dt>City</dt><dd>Ocos</dd>\n<dt>Country</dt><dd>GT</dd>\n<dt>Max Temp</dt><dd>89.78 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Non Stop</dd>\n<dt>City</dt><dd>Bougouni</dd>\n<dt>Country</dt><dd>ML</dd>\n<dt>Max Temp</dt><dd>84.9 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Movenpick Hotel Doha</dd>\n<dt>City</dt><dd>Doha</dd>\n<dt>Country</dt><dd>QA</dd>\n<dt>Max Temp</dt><dd>80.58 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sunimit Mansion</dd>\n<dt>City</dt><dd>Phangnga</dd>\n<dt>Country</dt><dd>TH</dd>\n<dt>Max Temp</dt><dd>78.84 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Beach Rotana</dd>\n<dt>City</dt><dd>Abu Dhabi</dd>\n<dt>Country</dt><dd>AE</dd>\n<dt>Max Temp</dt><dd>80.62 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Bungalow 63</dd>\n<dt>City</dt><dd>Hambantota</dd>\n<dt>Country</dt><dd>LK</dd>\n<dt>Max Temp</dt><dd>80.98 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>LIKWALE LODGE</dd>\n<dt>City</dt><dd>Mayumba</dd>\n<dt>Country</dt><dd>GA</dd>\n<dt>Max Temp</dt><dd>77.43 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Holiday Inn Express & Suites Charleston-North, an IHG Hotel</dd>\n<dt>City</dt><dd>Goose Creek</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>77.95 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Vitória Palace</dd>\n<dt>City</dt><dd>Vila Velha</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>77.95 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Auki Motel</dd>\n<dt>City</dt><dd>Auki</dd>\n<dt>Country</dt><dd>SB</dd>\n<dt>Max Temp</dt><dd>82.27 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Beatitude de Grand Lahou</dd>\n<dt>City</dt><dd>Grand-Lahou</dd>\n<dt>Country</dt><dd>CI</dd>\n<dt>Max Temp</dt><dd>80.65 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>guarderia imss papalote</dd>\n<dt>City</dt><dd>Socorro</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>88.29 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>TDC Village (Hundred Man Camp)</dd>\n<dt>City</dt><dd>Port Keats</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Max Temp</dt><dd>81.03 °F</dd>\n</dl>\n',
 "\n<dl>\n<dt>Hotel Name</dt><dd>Marriott's Ko Olina Beach Club</dd>\n<dt>City</dt><dd>Makakilo City</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Max Temp</dt><dd>80.92 °F</dd>\n</dl>\n",
 '\n<dl>\n<dt>Hotel Name</dt><dd>VSU Hostel</dd>\n<dt>City</dt><dd>Kilim</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Max Temp</dt><dd>80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Casa Dora, Bubaque</dd>\n<dt>City</dt><dd>Bubaque</dd>\n<dt>Country</dt><dd>GW</dd>\n<dt>Max Temp</dt><dd>77.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Fengshui Residence</dd>\n<dt>City</dt><dd>Port-Gentil</dd>\n<dt>Country</dt><dd>GA</dd>\n<dt>Max Temp</dt><dd>76.96 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Casa do Ian😎</dd>\n<dt>City</dt><dd>Jacareacanga</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Max Temp</dt><dd>75.34 °F</dd>\n</dl>\n',

In [60]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))